import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css"; // Pfad zu der globals.css Datei

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "APIarist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
